//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarResonanceDpsAnalysis.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 678150498 (Group 1) 的本地化字符串。
        /// </summary>
        public static string About_Community_GroupOne {
            get {
                return ResourceManager.GetString("About_Community_GroupOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1022797551 (Group 2) 的本地化字符串。
        /// </summary>
        public static string About_Community_GroupTwo {
            get {
                return ResourceManager.GetString("About_Community_GroupTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you cannot access GitHub or want to find teammates, join the Tencent QQ groups: 的本地化字符串。
        /// </summary>
        public static string About_Community_Invite {
            get {
                return ResourceManager.GetString("About_Community_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To contribute, please fork the repository and submit a pull request. 的本地化字符串。
        /// </summary>
        public static string About_Contribution {
            get {
                return ResourceManager.GetString("About_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (C) 2025 anying1073/StarResonanceDps Team. 的本地化字符串。
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尻鸭（ihonliu） 的本地化字符串。
        /// </summary>
        public static string About_Developer_Ihonliu {
            get {
                return ResourceManager.GetString("About_Developer_Ihonliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 惊奇猫猫盒 (anying1073: project founder) 的本地化字符串。
        /// </summary>
        public static string About_Developer_Lead {
            get {
                return ResourceManager.GetString("About_Developer_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青岚宗王腾 的本地化字符串。
        /// </summary>
        public static string About_Developer_QingLan {
            get {
                return ResourceManager.GetString("About_Developer_QingLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 露詩（Rocy-June） 的本地化字符串。
        /// </summary>
        public static string About_Developer_RocyJune {
            get {
                return ResourceManager.GetString("About_Developer_RocyJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contributors for this release (in no particular order): 的本地化字符串。
        /// </summary>
        public static string About_Developers_Label {
            get {
                return ResourceManager.GetString("About_Developers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tool requires no client modifications and stays within the game&apos;s terms of service. It helps players understand combat data, reduce unnecessary effort, and improve the gameplay experience. Please do not use the results for power discrimination or any behaviour that harms the community. 的本地化字符串。
        /// </summary>
        public static string About_Intro_Details {
            get {
                return ResourceManager.GetString("About_Intro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A combat data analytics tool built for BPSR players. 的本地化字符串。
        /// </summary>
        public static string About_Intro_Primary {
            get {
                return ResourceManager.GetString("About_Intro_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This project is open source at 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_Prefix {
            get {
                return ResourceManager.GetString("About_OpenSource_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/anying1073/StarResonanceDps 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_OpenSource_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , If you encounter any issues, please open an issue there. 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_Suffix {
            get {
                return ResourceManager.GetString("About_OpenSource_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by .NET 8, Licensed under the GNU AGPL v3. 的本地化字符串。
        /// </summary>
        public static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special thanks to 的本地化字符串。
        /// </summary>
        public static string About_Thanks_Prefix {
            get {
                return ResourceManager.GetString("About_Thanks_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/dmlgzs/StarResonanceDamageCounter 的本地化字符串。
        /// </summary>
        public static string About_Thanks_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_Thanks_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for supporting and inspiring this project. 的本地化字符串。
        /// </summary>
        public static string About_Thanks_Suffix {
            get {
                return ResourceManager.GetString("About_Thanks_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version: 的本地化字符串。
        /// </summary>
        public static string About_Version_Label {
            get {
                return ResourceManager.GetString("About_Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close application? 的本地化字符串。
        /// </summary>
        public static string App_Exit_Confirm_Content {
            get {
                return ResourceManager.GetString("App_Exit_Confirm_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        public static string App_Exit_Confirm_Title {
            get {
                return ResourceManager.GetString("App_Exit_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarResonance ToolBox 的本地化字符串。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frost Mage 的本地化字符串。
        /// </summary>
        public static string Classes_FrostMage {
            get {
                return ResourceManager.GetString("Classes_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heavy Guardian 的本地化字符串。
        /// </summary>
        public static string Classes_HeavyGuardian {
            get {
                return ResourceManager.GetString("Classes_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marksman 的本地化字符串。
        /// </summary>
        public static string Classes_Marksman {
            get {
                return ResourceManager.GetString("Classes_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield Knight 的本地化字符串。
        /// </summary>
        public static string Classes_ShieldKnight {
            get {
                return ResourceManager.GetString("Classes_ShieldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soul Musician 的本地化字符串。
        /// </summary>
        public static string Classes_SoulMusician {
            get {
                return ResourceManager.GetString("Classes_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stormblade 的本地化字符串。
        /// </summary>
        public static string Classes_Stormblade {
            get {
                return ResourceManager.GetString("Classes_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verdant Oracle 的本地化字符串。
        /// </summary>
        public static string Classes_VerdantOracle {
            get {
                return ResourceManager.GetString("Classes_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wind Knight 的本地化字符串。
        /// </summary>
        public static string Classes_WindKnight {
            get {
                return ResourceManager.GetString("Classes_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrostBeam 的本地化字符串。
        /// </summary>
        public static string ClassSpec_FrostMageFrostBeam {
            get {
                return ResourceManager.GetString("ClassSpec_FrostMageFrostBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icicle 的本地化字符串。
        /// </summary>
        public static string ClassSpec_FrostMageIcicle {
            get {
                return ResourceManager.GetString("ClassSpec_FrostMageIcicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block 的本地化字符串。
        /// </summary>
        public static string ClassSpec_HeavyGuardianBlock {
            get {
                return ResourceManager.GetString("ClassSpec_HeavyGuardianBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earthfort 的本地化字符串。
        /// </summary>
        public static string ClassSpec_HeavyGuardianEarthfort {
            get {
                return ResourceManager.GetString("ClassSpec_HeavyGuardianEarthfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Falconry 的本地化字符串。
        /// </summary>
        public static string ClassSpec_MarksmanFalconry {
            get {
                return ResourceManager.GetString("ClassSpec_MarksmanFalconry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wildpack 的本地化字符串。
        /// </summary>
        public static string ClassSpec_MarksmanWildpack {
            get {
                return ResourceManager.GetString("ClassSpec_MarksmanWildpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery 的本地化字符串。
        /// </summary>
        public static string ClassSpec_ShieldKnightRecovery {
            get {
                return ResourceManager.GetString("ClassSpec_ShieldKnightRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield 的本地化字符串。
        /// </summary>
        public static string ClassSpec_ShieldKnightShield {
            get {
                return ResourceManager.GetString("ClassSpec_ShieldKnightShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concerto 的本地化字符串。
        /// </summary>
        public static string ClassSpec_SoulMusicianConcerto {
            get {
                return ResourceManager.GetString("ClassSpec_SoulMusicianConcerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dissonance 的本地化字符串。
        /// </summary>
        public static string ClassSpec_SoulMusicianDissonance {
            get {
                return ResourceManager.GetString("ClassSpec_SoulMusicianDissonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IaidoSlash 的本地化字符串。
        /// </summary>
        public static string ClassSpec_StormbladeIaidoSlash {
            get {
                return ResourceManager.GetString("ClassSpec_StormbladeIaidoSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoonStrike 的本地化字符串。
        /// </summary>
        public static string ClassSpec_StormbladeMoonStrike {
            get {
                return ResourceManager.GetString("ClassSpec_StormbladeMoonStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string ClassSpec_Unknown {
            get {
                return ResourceManager.GetString("ClassSpec_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LifeBind 的本地化字符串。
        /// </summary>
        public static string ClassSpec_VerdantOracleLifeBind {
            get {
                return ResourceManager.GetString("ClassSpec_VerdantOracleLifeBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smite 的本地化字符串。
        /// </summary>
        public static string ClassSpec_VerdantOracleSmite {
            get {
                return ResourceManager.GetString("ClassSpec_VerdantOracleSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skyward 的本地化字符串。
        /// </summary>
        public static string ClassSpec_WindKnightSkyward {
            get {
                return ResourceManager.GetString("ClassSpec_WindKnightSkyward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VanGuard 的本地化字符串。
        /// </summary>
        public static string ClassSpec_WindKnightVanGuard {
            get {
                return ResourceManager.GetString("ClassSpec_WindKnightVanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        public static string Common_Action_Open {
            get {
                return ResourceManager.GetString("Common_Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string Common_Dash {
            get {
                return ResourceManager.GetString("Common_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Classes 的本地化字符串。
        /// </summary>
        public static string DamageReference_Classes_All {
            get {
                return ResourceManager.GetString("DamageReference_Classes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data is for entertainment and reference only. Do not use it for power discrimination or any behaviour that harms the community; violations will result in permanent revocation. 的本地化字符串。
        /// </summary>
        public static string DamageReference_Disclaimer {
            get {
                return ResourceManager.GetString("DamageReference_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Breakdown 的本地化字符串。
        /// </summary>
        public static string DamageReference_Header_Title {
            get {
                return ResourceManager.GetString("DamageReference_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data yet 的本地化字符串。
        /// </summary>
        public static string DamageReference_NoData {
            get {
                return ResourceManager.GetString("DamageReference_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Reference 的本地化字符串。
        /// </summary>
        public static string DamageReference_Ribbon_Title {
            get {
                return ResourceManager.GetString("DamageReference_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Reference 的本地化字符串。
        /// </summary>
        public static string DamageReference_Table_Title {
            get {
                return ResourceManager.GetString("DamageReference_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddSampleData 的本地化字符串。
        /// </summary>
        public static string Debug_AddSampleData {
            get {
                return ResourceManager.GetString("Debug_AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Test Log 的本地化字符串。
        /// </summary>
        public static string Debug_AddTestLog {
            get {
                return ResourceManager.GetString("Debug_AddTestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scroll 的本地化字符串。
        /// </summary>
        public static string Debug_AutoScroll {
            get {
                return ResourceManager.GetString("Debug_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About View 的本地化字符串。
        /// </summary>
        public static string Debug_Button_About {
            get {
                return ResourceManager.GetString("Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Reference View 的本地化字符串。
        /// </summary>
        public static string Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Pcap 的本地化字符串。
        /// </summary>
        public static string Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings View 的本地化字符串。
        /// </summary>
        public static string Debug_Button_Settings {
            get {
                return ResourceManager.GetString("Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Breakdown View 的本地化字符串。
        /// </summary>
        public static string Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Logs 的本地化字符串。
        /// </summary>
        public static string Debug_ClearLogs {
            get {
                return ResourceManager.GetString("Debug_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter: 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Label {
            get {
                return ResourceManager.GetString("Debug_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Level {
            get {
                return ResourceManager.GetString("Debug_Filter_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter logs by message or category content 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Tooltip {
            get {
                return ResourceManager.GetString("Debug_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug utilities 的本地化字符串。
        /// </summary>
        public static string Debug_Group_Title {
            get {
                return ResourceManager.GetString("Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Category {
            get {
                return ResourceManager.GetString("Debug_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Level {
            get {
                return ResourceManager.GetString("Debug_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Message {
            get {
                return ResourceManager.GetString("Debug_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Time {
            get {
                return ResourceManager.GetString("Debug_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load PCAP 的本地化字符串。
        /// </summary>
        public static string Debug_LoadPcap {
            get {
                return ResourceManager.GetString("Debug_LoadPcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Debug_Localization_Apply {
            get {
                return ResourceManager.GetString("Debug_Localization_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string Debug_Localization_Language {
            get {
                return ResourceManager.GetString("Debug_Localization_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string Debug_Localization_Test {
            get {
                return ResourceManager.GetString("Debug_Localization_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Key: 的本地化字符串。
        /// </summary>
        public static string Debug_Localization_TestKey {
            get {
                return ResourceManager.GetString("Debug_Localization_TestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Logs 的本地化字符串。
        /// </summary>
        public static string Debug_SaveLogs {
            get {
                return ResourceManager.GetString("Debug_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filtered:  的本地化字符串。
        /// </summary>
        public static string Debug_Status_FilteredPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  logs 的本地化字符串。
        /// </summary>
        public static string Debug_Status_FilteredSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last:  的本地化字符串。
        /// </summary>
        public static string Debug_Status_LastPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_LastPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total:  的本地化字符串。
        /// </summary>
        public static string Debug_Status_TotalPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  logs 的本地化字符串。
        /// </summary>
        public static string Debug_Status_TotalSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme switch test text 的本地化字符串。
        /// </summary>
        public static string Debug_ThemeTestText {
            get {
                return ResourceManager.GetString("Debug_ThemeTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse click-through enabled 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_Indicator_ClickThrough_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_Indicator_ClickThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Always on Top 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_Indicator_WindowTopMost_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_Indicator_WindowTopMost_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_TestButton_Content {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Test Item 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_TestButton_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About View 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Button_About {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Reference View 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pcap Test 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings View 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Button_Settings {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Breakdown View 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug utilities 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_Group_Title {
            get {
                return ResourceManager.GetString("MainView_Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme switch test text 的本地化字符串。
        /// </summary>
        public static string MainView_Debug_ThemeTest {
            get {
                return ResourceManager.GetString("MainView_Debug_ThemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarResonance ToolBox 的本地化字符串。
        /// </summary>
        public static string MainView_Header_Title {
            get {
                return ResourceManager.GetString("MainView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Official] StarResonanceToolBox Team 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Author_OfficialTeam {
            get {
                return ResourceManager.GetString("MainView_Plugin_Author_OfficialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Off 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_AutoRunState_Disabled {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoRunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto On 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_AutoRunState_Enabled {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoRunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_AutoStart {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides DPS statistics and skill breakdown tools 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_DpsTool_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS Toolkit 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_DpsTool_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Label_Author {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intro: 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Label_Intro {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickly calculates optimal module combinations 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_ModuleSolver_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Solver 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_ModuleSolver_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community-driven tracker for Pig Nabo routes and locations 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_PigTracker_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pig Nabo Status Tracker 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_PigTracker_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search... 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Search_PlaceHolder {
            get {
                return ResourceManager.GetString("MainView_Plugin_Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Settings {
            get {
                return ResourceManager.GetString("MainView_Plugin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_State_Inactive {
            get {
                return ResourceManager.GetString("MainView_Plugin_State_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_State_Running {
            get {
                return ResourceManager.GetString("MainView_Plugin_State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin SDK coming soon! 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_ThirdPartySdkTips {
            get {
                return ResourceManager.GetString("MainView_Plugin_ThirdPartySdkTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Training_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_Training_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_Training_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_Training_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crowdsourced live data for each channel&apos;s world boss status 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_WorldBoss_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World Boss Status Tracker 的本地化字符串。
        /// </summary>
        public static string MainView_Plugin_WorldBoss_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string MainView_PluginList_Title {
            get {
                return ResourceManager.GetString("MainView_PluginList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Snapshot Mode 的本地化字符串。
        /// </summary>
        public static string Menu_ExitSnapshotMode {
            get {
                return ResourceManager.GetString("Menu_ExitSnapshotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Battle 的本地化字符串。
        /// </summary>
        public static string Menu_History_Current {
            get {
                return ResourceManager.GetString("Menu_History_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Battle 的本地化字符串。
        /// </summary>
        public static string Menu_History_Total {
            get {
                return ResourceManager.GetString("Menu_History_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solo/Traning Mode 的本地化字符串。
        /// </summary>
        public static string Menu_Personal_Training_Mode {
            get {
                return ResourceManager.GetString("Menu_Personal_Training_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Every Fight 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Always {
            get {
                return ResourceManager.GetString("Menu_Record_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore fights &lt; 1 min 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Skip1Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore fights &lt; 2 min 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Skip2Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip2Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Options 的本地化字符串。
        /// </summary>
        public static string Menu_RecordSettings {
            get {
                return ResourceManager.GetString("Menu_RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Total Damage 的本地化字符串。
        /// </summary>
        public static string Menu_ShowTotal {
            get {
                return ResourceManager.GetString("Menu_ShowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Display 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_All {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 10 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top10 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 15 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top15 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 5 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top5 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 8 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top8 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Boss Only 的本地化字符串。
        /// </summary>
        public static string Menu_StatisticBoss {
            get {
                return ResourceManager.GetString("Menu_StatisticBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary masking 的本地化字符串。
        /// </summary>
        public static string Menu_TemporaryMaskPlayerName {
            get {
                return ResourceManager.GetString("Menu_TemporaryMaskPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training Mode 的本地化字符串。
        /// </summary>
        public static string Menu_Training {
            get {
                return ResourceManager.GetString("Menu_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze modules 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Analyze_Button {
            get {
                return ResourceManager.GetString("ModuleSolve_Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude stats (conflicts with targets) [type to search] 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ExcludeProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_ExcludeProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desired level: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ExpectedLevel_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ExpectedLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Solver 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Header_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_All {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defense 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Defense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module type: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offense 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Offense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Support {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat 1: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property1_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat 2: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property2_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat 3: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property3_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat 4: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property4_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat 5: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property5_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stat priority 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Attribute {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by: 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level priority 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Level {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target stats and levels (0 = default) [type to search] 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_TargetProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_TargetProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After opening this window, change zone or relog before analyzing. Right-click a stat option to clear it. 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_UsingTip {
            get {
                return ResourceManager.GetString("ModuleSolve_UsingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMBT (Western) 的本地化字符串。
        /// </summary>
        public static string NumberDisplay_KMB {
            get {
                return ResourceManager.GetString("NumberDisplay_KMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wan (East Asian) 的本地化字符串。
        /// </summary>
        public static string NumberDisplay_Wan {
            get {
                return ResourceManager.GetString("NumberDisplay_Wan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current 的本地化字符串。
        /// </summary>
        public static string ScopeTime_Current {
            get {
                return ResourceManager.GetString("ScopeTime_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        public static string ScopeTime_Total {
            get {
                return ResourceManager.GetString("ScopeTime_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard all changes? Unsaved changes will be lost. 的本地化字符串。
        /// </summary>
        public static string Settings_CancelConfirm_Message {
            get {
                return ResourceManager.GetString("Settings_CancelConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard Changes 的本地化字符串。
        /// </summary>
        public static string Settings_CancelConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_CancelConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character UID 的本地化字符串。
        /// </summary>
        public static string Settings_Character_Uid {
            get {
                return ResourceManager.GetString("Settings_Character_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your character UID (number)
        ///How to get: After a fight, your character will automatically appear in the stats window 的本地化字符串。
        /// </summary>
        public static string Settings_Character_Uid_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Character_Uid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear data after combat 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_ClearAfterBattle {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset on map change 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_ClearAfterTeleport {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS Update Interval 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateInterval {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only effective in Active mode
        ///Recommended: 500-2000 milliseconds 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateInterval_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS Update Mode 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateMode {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer Based 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateMode_Active {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateMode_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real Time 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateMode_Passive {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateMode_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real Time: Event-driven updates
        ///
        ///Timer Based: Timer-based periodic updates
        ///(low CPU usage, configurable refresh interval) 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_DpsUpdateMode_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Combat_DpsUpdateMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Record Limit 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_MaxHistoryCount {
            get {
                return ResourceManager.GetString("Settings_Combat_MaxHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of battle records to keep (5-50) 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_MaxHistoryCount_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Combat_MaxHistoryCount_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ms 的本地化字符串。
        /// </summary>
        public static string Settings_Common_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Common_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 records 的本地化字符串。
        /// </summary>
        public static string Settings_Common_Records {
            get {
                return ResourceManager.GetString("Settings_Common_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 s 的本地化字符串。
        /// </summary>
        public static string Settings_Common_Seconds {
            get {
                return ResourceManager.GetString("Settings_Common_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number display mode 的本地化字符串。
        /// </summary>
        public static string Settings_Display_NumberMode {
            get {
                return ResourceManager.GetString("Settings_Display_NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overlay opacity 的本地化字符串。
        /// </summary>
        public static string Settings_Display_Opacity {
            get {
                return ResourceManager.GetString("Settings_Display_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask player names 的本地化字符串。
        /// </summary>
        public static string Settings_Display_PlayerNameBlur {
            get {
                return ResourceManager.GetString("Settings_Display_PlayerNameBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Heading {
            get {
                return ResourceManager.GetString("Settings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow system 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Português (Brasil) 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Portuguese {
            get {
                return ResourceManager.GetString("Settings_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Adapter 的本地化字符串。
        /// </summary>
        public static string Settings_NetworkAdapter_Label {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Settings_NetworkAdapterAutoSelect_Button {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapterAutoSelect_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network adapter auto select failed, please check you have proper network connections 的本地化字符串。
        /// </summary>
        public static string Settings_NetworkAdapterAutoSelect_Failed {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapterAutoSelect_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use data results to discriminate or harm the game community environment. 的本地化字符串。
        /// </summary>
        public static string Settings_PlayerNameMask_Warning_Message {
            get {
                return ResourceManager.GetString("Settings_PlayerNameMask_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Settings_PlayerNameMask_Warning_Title {
            get {
                return ResourceManager.GetString("Settings_PlayerNameMask_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust manually when auto detection fails 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Basic_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Basic_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set your character UID for Solo/Training mode 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Character_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Character_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Character_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Character_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Clear data after combat] resets only the current data, not the total. 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Combat_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Combat_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Display_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface display preferences 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press [Delete] to clear the selected shortcut 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Shortcut_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Shortcut_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize your own tool box 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Theme_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Data 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ClearData {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus this box and press a shortcut (e.g. F9). Press Delete to clear. 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ClearData_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Through 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_MouseThrough {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus this box and press a shortcut (e.g. Ctrl+F6). Press Delete to clear. 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_MouseThrough_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle DPS Window 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ToggleDps {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ToggleDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus this box and press a shortcut (e.g. F10). Press Delete to clear. 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ToggleDps_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ToggleDps_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on Top 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_TopMost {
            get {
                return ResourceManager.GetString("Settings_Shortcut_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus this box and press a shortcut (e.g. Ctrl+F9). Press Delete to clear. 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_TopMost_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_TopMost_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string Settings_Switch_Off {
            get {
                return ResourceManager.GetString("Settings_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string Settings_Switch_On {
            get {
                return ResourceManager.GetString("Settings_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Image 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_BackgroundImage {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image... 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_SelectImage {
            get {
                return ResourceManager.GetString("Settings_Theme_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Color 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_WindowColor {
            get {
                return ResourceManager.GetString("Settings_Theme_WindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage distribution 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realtime DPS/HPS/DTPS charts 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_RealtimeChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_RealtimeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill contribution chart 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_ShareChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Breakdown 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Header_Title {
            get {
                return ResourceManager.GetString("SkillBreakdown_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Badge: 190 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Badge {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: 60 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Level {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Sample Name-- 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Name {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power: 25000 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Power {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UID: 123456 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Uid {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average hit 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical hits 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical damage 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crit rate 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Times hit 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hits 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lucky hits 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lucky damage 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luck rate 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal damage 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total damage 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagine a bar chart here 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_BarChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details placeholder 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagine a data table here 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Form {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph placeholder 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagine a line chart here 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_LineChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagine a pie chart here 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_PieChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage distribution 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Section_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage info 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Section_DamageInfo {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healing 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Healing {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Output {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Summary {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Taken 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Tanking {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Tanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7106 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.92K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.67% 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 29.01K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0% 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 28.71K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 42.64K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage 的本地化字符串。
        /// </summary>
        public static string StatisticType_Damage {
            get {
                return ResourceManager.GetString("StatisticType_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healing 的本地化字符串。
        /// </summary>
        public static string StatisticType_Healing {
            get {
                return ResourceManager.GetString("StatisticType_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NPC Dmg In 的本地化字符串。
        /// </summary>
        public static string StatisticType_NpcTakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_NpcTakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dmg In 的本地化字符串。
        /// </summary>
        public static string StatisticType_TakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_TakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle: Full / Current 的本地化字符串。
        /// </summary>
        public static string Tooltip_ToggleScope {
            get {
                return ResourceManager.GetString("Tooltip_ToggleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boss Status Tracker 的本地化字符串。
        /// </summary>
        public static string Window_BossTracker_Title {
            get {
                return ResourceManager.GetString("Window_BossTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Reference 的本地化字符串。
        /// </summary>
        public static string Window_DamageReference_Title {
            get {
                return ResourceManager.GetString("Window_DamageReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug View 的本地化字符串。
        /// </summary>
        public static string Window_Debug_Title {
            get {
                return ResourceManager.GetString("Window_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS Statistics 的本地化字符串。
        /// </summary>
        public static string Window_DpsStatistics_Title {
            get {
                return ResourceManager.GetString("Window_DpsStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Solver 的本地化字符串。
        /// </summary>
        public static string Window_ModuleSolve_Title {
            get {
                return ResourceManager.GetString("Window_ModuleSolve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Details 的本地化字符串。
        /// </summary>
        public static string Window_SkillBreakdown_Title {
            get {
                return ResourceManager.GetString("Window_SkillBreakdown_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training 的本地化字符串。
        /// </summary>
        public static string Window_Training_Title {
            get {
                return ResourceManager.GetString("Window_Training_Title", resourceCulture);
            }
        }
    }
}
